	-- items
	["raw_meat"]			= {["name"] = "raw_meat",		["label"] = "Raw Meat",		["weight"] = 50, 	["type"] = "item",	["image"] = "rsg_raw_meat.png",				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "ready for cooking"},
	["cooked_meat"]			= {["name"] = "cooked_meat",		["label"] = "Cooked Meat",	["weight"] = 50, 	["type"] = "item",	["image"] = "rsg_cooked_meat.png",			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "ready to eat"},
	["fishmeat"]			= {["name"] = "fishmeat",		["label"] = "Fish Meat",	["weight"] = 50, 	["type"] = "item",	["image"] = "rsg_fishmeat.png",				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "ready for cooking"},
	["cooked_fishmeat"]		= {["name"] = "cooked_fishmeat",	["label"] = "Fish Steak",	["weight"] = 50, 	["type"] = "item",	["image"] = "rsg_cooked_fishmeat.png",			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "ready to eat"},
	["cookkit"]			= {["name"] = "cookkit",		["label"] = "Cooking Kit",	["weight"] = 500, 	["type"] = "item",	["image"] = "rsg_cookkit.png",				['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	["description"] = "used for cooking"},
	['smallfish']			= {['name'] = 'smallfish',		['label'] = 'Small Fish',	['weight'] = 100,	['type'] = 'item',	['image'] = 'rsg_smallfish.png',			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['mediumfish']			= {['name'] = 'mediumfish',		['label'] = 'Medium Fish',	['weight'] = 200,	['type'] = 'item',	['image'] = 'rsg_mediumfish.png',			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},
	['largefish']			= {['name'] = 'largefish',		['label'] = 'Large Fish',	['weight'] = 300,	['type'] = 'item',	['image'] = 'rsg_largefish.png',			['unique'] = false,		['useable'] = true,		['shouldClose'] = true,	['combinable'] = nil,	['level'] = 0,	['description'] = 'used for fishing'},

	-- should already be in weapons 
	['weapon_melee_knife']	= {['name'] = 'weapon_melee_knife',	['label'] = 'Knife',	['weight'] = 100,	['type'] = 'weapon',	['ammotype'] = nil,					['image'] = 'weapon_melee_knife.png',	['unique'] = true,	['useable'] = true,		['level'] = 0,		['description'] = 'Hunting Knife'},
